### ISSUE TITLE
"Hacktoberfest is here!" button is hard coded to Tighten organisation

### ISSUE THREAD

**Issue by damcclean** [tighten/ozzie#69]
I've just setup [my own instance of Ozzie](https://ozzie.doublethree.digital/) to see an overview of all my open-source projects. 

I've updated it with all my repos and changed the `APP_ORG` in my `.env` file. However, one thing I've noticed is that the 'Hacktoberfest is here!' directly links to the a Github issue search with the Tighen org hard coded.

Would you be happy for me to submit a pull request to make the organisation updatable? Probably through an `.env` value?

**Comment by vmitchell85** [comment]
Did some digging into a method of implementing this. It seems like you could use `APP_ORG` from the `.env` but `APP_ORG` is only used for text as far as I can tell.

Since any repo can be added to the `projects.json` file I think either providing direction on using the `APP_ORG` config setting to be the desired GitHub org / account, or adding a new config variable for the preferred GitHub org / account would  work.

Decided not to create a PR to allow discussion and not step on @damcclean's toes.

Streamed my thoughts live on https://twitch.tv/hacktobercon

**Comment by damcclean** [comment]
Nice! I watched back part of your stream where you covered the issue - The secret is to clear the Laravel cache to refresh the projects, it hit me too.

I thought about getting it from `APP_ORG` but it seems to be the variable that's used in the `<title>` tag, so if you wanted the title to be `Ozzie - Double Three Digital`, you'd have to set this...

```
APP_ORG="Double Three Digital"
```

This wouldn't work because obviously my organisation name doesn't have spaces in it. 

I wonder if it would be better that `APP_NAME` had the organisation name with the spaces and `APP_ORG` is just the name of the Github organisation that can be plugged into the button URL for example?

I'm happy to implement it if someone from Tighten's also happy with that approach.

**Comment by sbine** [comment]
@damcclean I like your suggestion and would accept a PR using `APP_NAME` for the org's human-readable name, and `APP_ORG` for the GitHub organization.

**Comment by damcclean** [comment]
Awesome! I'll try and remember to PR that this weekend.

**Comment by sbine** [comment]
Fixed in #83
